Pong In A Box: C:/Users/katabeta/Documents/GitHub/PongInABox/mains/PrinterTest.cpp File Reference
PrinterTest.cpp File Reference
Functions
void setup ()
void loop ()
Variables
Adafruit_IS31FL3731 ledmatrix74 = Adafruit_IS31FL3731()
Adafruit_IS31FL3731 ledmatrix75 = Adafruit_IS31FL3731()
int nums [] = {1,2,3,4,5,6,7,8,9}
ErrorCodes errorCodes = ErrorCodes()
bool print = true
String testString = "TESTING, testing. 123!@$"
Hardware hardware = Hardware()
Function Documentation
void setup ()
Definition at line 19 of file PrinterTest.cpp.
References Adafruit_IS31FL3731::begin(), ErrorCodes::DISP_NOT_FOUND, hardware, Adafruit_GFX::setRotation(), and ErrorCodes::writeErrorCode().
void loop ()
Definition at line 35 of file PrinterTest.cpp.
References Adafruit_IS31FL3731::printText(), and testString.
Variable Documentation
Adafruit_IS31FL3731 ledmatrix74 = Adafruit_IS31FL3731()
Definition at line 7 of file PrinterTest.cpp.
Adafruit_IS31FL3731 ledmatrix75 = Adafruit_IS31FL3731()
Definition at line 8 of file PrinterTest.cpp.
int nums[] = {1,2,3,4,5,6,7,8,9}
Definition at line 10 of file PrinterTest.cpp.
ErrorCodes errorCodes = ErrorCodes()
Definition at line 12 of file PrinterTest.cpp.
bool print = true
Definition at line 14 of file PrinterTest.cpp.
String testString = "TESTING, testing. 123!@$"
Definition at line 15 of file PrinterTest.cpp.
Referenced by loop().
Hardware hardware = Hardware()
Definition at line 17 of file PrinterTest.cpp.
Referenced by setup().