Pong In A Box: Adafruit_IS31FL3731 Class Reference
Adafruit_IS31FL3731 Class Reference
Inherits Adafruit_GFX.
Public Member Functions
Adafruit_IS31FL3731 (void)
void audioSync (boolean sync)
boolean begin (uint8_t addr=ISSI_ADDR_DEFAULT)
void clear (void)
void displayFrame (uint8_t frame)
void drawPixel (int16_t x, int16_t y, uint16_t color)
void printText (uint8_t x, uint8_t y, String text, uint8_t brightness, bool clearAfter, bool scroll, uint8_t scrollSpeed, uint8_t spacing)
void setFrame (uint8_t b)
void setLEDPWM (uint8_t lednum, uint8_t pwm, uint8_t bank=0)
Public Member Functions inherited from Adafruit_GFX
Adafruit_GFX (int16_t w, int16_t h)
void cp437 (boolean x=true)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawChar (int16_t x, int16_t y, unsigned char c, uint16_t color, uint16_t bg, uint8_t size)
void drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
virtual void drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
virtual void drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
virtual void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
virtual void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
void drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void drawXBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
virtual void fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
void fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
virtual void fillScreen (uint16_t color)
void fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
int16_t getCursorX (void) const
int16_t getCursorY (void) const
uint8_t getRotation (void) const
void getTextBounds (char *string, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
void getTextBounds (const __FlashStringHelper *s, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
int16_t height (void) const
virtual void invertDisplay (boolean i)
void setCursor (int16_t x, int16_t y)
void setFont (const GFXfont *f=NULL)
void setRotation (uint8_t r)
void setTextColor (uint16_t c)
void setTextColor (uint16_t c, uint16_t bg)
void setTextSize (uint8_t s)
void setTextWrap (boolean w)
int16_t width (void) const
virtual void write (uint8_t)
Private Member Functions
uint8_t readRegister8 (uint8_t bank, uint8_t reg)
void selectBank (uint8_t bank)
void writeRegister8 (uint8_t bank, uint8_t reg, uint8_t data)
Private Attributes
uint8_t _frame
uint8_t _i2caddr
Additional Inherited Members
Protected Attributes inherited from Adafruit_GFX
boolean _cp437
int16_t _height
int16_t _width
int16_t cursor_x
int16_t cursor_y
GFXfont * gfxFont
const int16_t HEIGHT
uint8_t rotation
uint16_t textbgcolor
uint16_t textcolor
uint8_t textsize
const int16_t WIDTH
boolean wrap
Detailed Description
Todo:
update to the most recent version on github
Authors
modified from Limor Fried (ladyada), Andy Doro (andydoro), and (gragib) https://github.com/adafruit/Adafruit_IS31FL3731
Definition at line 29 of file Adafruit_IS31FL3731.h.
Constructor & Destructor Documentation
Adafruit_IS31FL3731::Adafruit_IS31FL3731 (void)
Definition at line 23 of file Adafruit_IS31FL3731.cpp.
Member Function Documentation
void Adafruit_IS31FL3731::audioSync (boolean sync)
Definition at line 191 of file Adafruit_IS31FL3731.cpp.
References writeRegister8().
Referenced by begin().
boolean Adafruit_IS31FL3731::begin (uint8_t addr = ISSI_ADDR_DEFAULT)
Definition at line 27 of file Adafruit_IS31FL3731.cpp.
References _frame, _i2caddr, audioSync(), clear(), displayFrame(), and writeRegister8().
void Adafruit_IS31FL3731::clear (void)
Definition at line 127 of file Adafruit_IS31FL3731.cpp.
References _frame, _i2caddr, and selectBank().
Referenced by begin(), Game::chooseDifficulty(), Game::playAgain(), and printText().
void Adafruit_IS31FL3731::displayFrame (uint8_t frame)
Definition at line 178 of file Adafruit_IS31FL3731.cpp.
References writeRegister8().
Referenced by begin().
void Adafruit_IS31FL3731::drawPixel (int16_t x, int16_t y, uint16_t color) virtual
Implements Adafruit_GFX.
Definition at line 149 of file Adafruit_IS31FL3731.cpp.
References _frame, Adafruit_GFX::getRotation(), and setLEDPWM().
void Adafruit_IS31FL3731::printText (uint8_t x, uint8_t y, String text, uint8_t brightness, bool clearAfter, bool scroll, uint8_t scrollSpeed, uint8_t spacing)
Prints the passed text on the display on which this method is called.
If you are calling this method on a pointer to a display, don't use exampleDisplay.printText(...); rather, use exampleDisplay->printText(...);
Display coordination system (x, y)
↓y x→ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
8 0, 8 1, 8 2, 8 3, 8 4, 8 5, 8 6, 8 7, 8 8, 8 9, 8 10, 8 11, 8 12, 8 13, 8 14, 8 15, 8
7 0, 7 1, 7 2, 7 3, 7 4, 7 5, 7 6, 7 7, 7 8, 7 9, 7 10, 7 11, 7 12, 7 13, 7 14, 7 15, 7
6 0, 6 1, 6 2, 6 3, 6 4, 6 5, 6 6, 6 7, 6 8, 6 9, 6 10, 6 11, 6 12, 6 13, 6 14, 6 15, 6
5 0, 5 1, 5 2, 3 5, 5 4, 5 5, 5 6, 5 7, 5 8, 5 9, 5 10, 5 11, 5 12, 5 13, 5 14, 5 15, 5
4 0, 4 1, 4 2, 4 3, 4 4, 4 5, 4 6, 4 7, 4 8, 4 9, 4 10, 4 11, 4 12, 4 13, 4 14, 4 15, 4
3 0, 3 1, 3 2, 3 3, 3 4, 3 5, 3 6, 3 7, 3 8, 3 9, 3 10, 3 11, 3 12, 3 13, 3 14, 3 15, 3
2 0, 2 1, 2 2, 2 3, 2 4, 2 5, 2 6, 2 7, 2 8, 2 9, 2 10, 2 11, 2 12, 2 13, 2 14, 2 15, 2
1 0, 1 1, 1 2, 1 3, 1 4, 1 5, 1 6, 1 7, 1 8, 1 9, 1 10, 1 11, 1 12, 1 13, 1 14, 1 15, 1
0 0, 0 1, 0 2, 0 3, 0 4, 0 5, 0 6, 0 7, 0 8, 0 9, 0 10, 0 11, 0 12, 0 13, 0 14, 0 15, 0
Parameters
x the x coordinate of the bottom left of your text, 0 is usually sufficient
y the y coordinate of the bottom left of your text, 0 is usually sufficient
text the text that you would like to print
brightness how bright you would like to display your text (0-254, where 0 is not lit up at all and 254 is the brightest)
clearAfter do you want to erase all of the text after it is done printing? You can do this manually as well by calling clear()
scroll do you want the text to scroll?
scrollSpeed the speed with which you want the text to scroll, with 1 being the lowest. The units for this variable are arbitrary
spacing the spacing, in pixels, that you want between each character of your text. 5 is usually sufficient. A spacing of 0 will result in every character being drawn over the others.
Todo:
can only print to one display at a time. Make it so that the update can be alternated
might need to update the whole display at once, not scroll
may need to scroll with blocks, not by pixel column to allow for update times of both displays and for an easy time of reading
is background brightness needed?
https://github.com/gragib/Adafruit_IS31FL3731/commit/59498f8dca9d06f3505ebd8a3831224d67e5059b examples/gfxdemo/gfxdemo.ino lines 84-104
Author
Irina Lavryonova (katabeta)
Definition at line 106 of file Adafruit_IS31FL3731.cpp.
References clear(), and Adafruit_GFX::drawChar().
Referenced by Game::chooseDifficulty(), Player::displayNumber(), Game::displayScore(), Game::playAgain(), and Pot::test().
uint8_t Adafruit_IS31FL3731::readRegister8 (uint8_t bank, uint8_t reg) private
Definition at line 211 of file Adafruit_IS31FL3731.cpp.
References _i2caddr, and selectBank().
void Adafruit_IS31FL3731::selectBank (uint8_t bank) private
Definition at line 184 of file Adafruit_IS31FL3731.cpp.
References _i2caddr.
Referenced by clear(), readRegister8(), and writeRegister8().
void Adafruit_IS31FL3731::setFrame (uint8_t b)
Definition at line 174 of file Adafruit_IS31FL3731.cpp.
References _frame.
void Adafruit_IS31FL3731::setLEDPWM (uint8_t lednum, uint8_t pwm, uint8_t bank = 0)
Definition at line 143 of file Adafruit_IS31FL3731.cpp.
References writeRegister8().
Referenced by drawPixel(), and Pot::test().
void Adafruit_IS31FL3731::writeRegister8 (uint8_t bank, uint8_t reg, uint8_t data) private
Definition at line 200 of file Adafruit_IS31FL3731.cpp.
References _i2caddr, and selectBank().
Referenced by audioSync(), begin(), displayFrame(), and setLEDPWM().
Member Data Documentation
uint8_t Adafruit_IS31FL3731::_frame private
Definition at line 49 of file Adafruit_IS31FL3731.h.
Referenced by begin(), clear(), drawPixel(), and setFrame().
uint8_t Adafruit_IS31FL3731::_i2caddr private
Definition at line 49 of file Adafruit_IS31FL3731.h.
Referenced by begin(), clear(), readRegister8(), selectBank(), and writeRegister8().