Pong In A Box: Pot Class Reference
Pot Class Reference
Public Member Functions
int getLEDNumRead (void)
int getLEDNumRead (double min, double max)
Pot (uint8_t pin, Adafruit_IS31FL3731 *display)
bool test (void)
Private Member Functions
double getNormalizedRead (void)
double getNormalizedRead (double min, double max)
Private Attributes
Adafruit_IS31FL3731 * display
int max
int min
int pin
Reference reference = Reference()
Detailed Description
Defines all of the necessary methods.
Parameters
pin the pin of the potentiometer. Please use Reference.
display the pointer to the display that is associated with this potentiometer (make sure that the display, potentiometer and button all belong to the same Player).
Todo:
use Adafruit_IS31FL3731::drawPixel() instead of Adafruit_IS31FL3731::setLEDPWM();
Author
Irina Lavryonova (katabeta)
Definition at line 8 of file Pot.h.
Constructor & Destructor Documentation
Pot::Pot (uint8_t pin, Adafruit_IS31FL3731 * display)
Constructor for the class.
Definition at line 21 of file Pot.cpp.
References display, and pin.
Member Function Documentation
int Pot::getLEDNumRead (void)
returns the LED number along the bottom of the display that the current status of this pot would light up.
Returns
the LED number (0-15) that the current status of this pot would light up.
Definition at line 32 of file Pot.cpp.
References getNormalizedRead().
Referenced by test().
int Pot::getLEDNumRead (double min, double max)
returns the LED number along the bottom of the display that the current status of this pot would light up.
Parameters
min the minimum raw value possible for the pot, some margin acceptable. Please use Reference.
max the maximum raw value possible for the pot, some margin acceptable. Please use Reference.
Returns
the LED number (0-15) that the current status of this pot would light up.
Definition at line 46 of file Pot.cpp.
References getNormalizedRead().
double Pot::getNormalizedRead (void) private
normalizes the raw reading from the potentiometer.
It ranges the output from 0 to 1, effectively giving the percentage. See: http://stats.stackexchange.com/questions/70801/how-to-normalize-data-to-0-1-range for more details. Feeds the getLEDNumRead() method.
Returns
normalized reading.
Definition at line 83 of file Pot.cpp.
References pin, Reference::potMax, Reference::potMin, and reference.
Referenced by getLEDNumRead().
double Pot::getNormalizedRead (double min, double max) private
normalizes the raw reading from the potentiometer.
It ranges the output from 0 to 1, effectively giving the percentage. See: http://stats.stackexchange.com/questions/70801/how-to-normalize-data-to-0-1-range for more details. Feeds the getLEDNumRead() method.
Parameters
min the minimum raw value possible for the pot, some margin acceptable. Please use Reference.
max the maximum raw value possible for the pot, some margin acceptable. Please use Reference.
Returns
normalized reading
Definition at line 99 of file Pot.cpp.
References min, and pin.
bool Pot::test (void)
allows the player to test that the pot is working as expected.
When the player is done testing, they can press their button to stop.
Test:
Returns
true when test has finished
Definition at line 59 of file Pot.cpp.
References display, getLEDNumRead(), pin, Adafruit_IS31FL3731::printText(), and Adafruit_IS31FL3731::setLEDPWM().
Referenced by Game::ready().
Member Data Documentation
Adafruit_IS31FL3731* Pot::display private
Holds the pointer to the display that is associated with this pot.
Definition at line 21 of file Pot.h.
Referenced by Pot(), and test().
int Pot::max private
Holds the maximum possible raw value of the pot.
If you are setting this value, please use Reference
Definition at line 16 of file Pot.h.
int Pot::min private
Holds the minimum possible raw value of the pot.
If you are setting this value, please use Reference
Definition at line 17 of file Pot.h.
Referenced by getNormalizedRead().
int Pot::pin private
Holds the pin of the pot.
If you are setting this value, please use Reference
Definition at line 15 of file Pot.h.
Referenced by getNormalizedRead(), Pot(), and test().
Reference Pot::reference = Reference() private
Initializes the constants library.
Definition at line 19 of file Pot.h.
Referenced by getNormalizedRead().