Pong In A Box: Pong Class Reference
Pong Class Reference
Inherits Game.
Public Member Functions
Pong (Player *player1, Player *player2, Button *button)
void start (void)
Private Member Functions
void drawField (void)
Private Member Functions inherited from Game
uint8_t chooseDifficulty (void)
void countdown (void)
void displayScore (void)
void drawLoseAnim (void)
void drawWinAnim (void)
Game (Player *player1, Player *player2, Button *button)
bool playAgain (void)
bool ready (void)
Detailed Description
Extends Game. This is the class where the bahaviour specific to the game of pong is defined.
Parameters
player1 The pointer to the first player of the game (P1, player whose number variable is 1).
player2 The pointer to the second player of the game (P2, player whose number variable is 2).
cofirmbutton The pointer to the button that isn't assigned to either of the players.
Test:
Definition at line 8 of file Pong.h.
Constructor & Destructor Documentation
Pong::Pong (Player * player1, Player * player2, Button * button)
Definition at line 19 of file Pong.cpp.
Member Function Documentation
void Pong::drawField (void) private
Referenced by start().
void Pong::start (void)
Call this method to start the game.
This method defines the sequence of events to play pong. At the end of the sequence, it asks the users if they want to play again. Public.
Todo:
NOT FINISHED
Definition at line 30 of file Pong.cpp.
References Game::chooseDifficulty(), drawField(), Game::playAgain(), and Game::ready().