Pong In A Box: Game Class Reference
Game Class Reference
Inherited by Pong [private].
Public Member Functions
uint8_t chooseDifficulty (void)
void countdown (void)
void displayScore (void)
void drawLoseAnim (Player *loser)
void drawWinAnim (Player *winner)
bool endGameReached (void)
Game (Player *player1, Player *player2, Button *confirmButton, bool winByLead, int scoreConstraint)
bool playAgain (void)
bool ready (void)
Private Attributes
Button * confirmButton
uint8_t difficulty
Player * p1
Player * p2
int scoreConstrant
bool winByLead
Detailed Description
Parameters
player1 the pointer to the first player of the game (P1, player whose number variable is 1).
player2 the pointer to the second player of the game (P2, player whose number variable is 2).
cofirmbutton the pointer to the button that isn't assigned to either of the players.
winByLead set to true if the winning condition of this game depends on one player leading the other by a certain amount. Give the winning lead amount in the scoreCostraint argument if set to true.
scoreConstraint top score that would serve as the winning condition (relative or absolute score)
Test:
Author
Irina Lavryonova (katabeta)
Definition at line 7 of file Game.h.
Member Function Documentation
uint8_t Game::chooseDifficulty (void)
Prompts the players to select a setting.
Test:
Definition at line 54 of file Game.cpp.
References Player::button, difficulty, Player::display, Button::get(), p1, p2, and Adafruit_IS31FL3731::printText().
Referenced by Pong::start().
void Game::countdown (void)
counts down from 3 to 0 on both of the screen to signal that the game is about to start and the players should be ready.
Test:
Definition at line 132 of file Game.cpp.
References Player::display, p1, and p2.
void Game::displayScore (void)
displays the score of both players on both of the displays, with the first player's score first and the second player's score second.
Make sure to Player::displayNumber() at some point before this so that the player knows which score is theirs.
Test:
Definition at line 121 of file Game.cpp.
References Player::display, p1, p2, Adafruit_IS31FL3731::printText(), and Player::score.
void Game::drawLoseAnim (Player * loser)
draws the losing animation on the losing player's display
Parameters
loser the pointer to the player who lost the game
Todo:
UNIMPLEMENTED
Definition at line 147 of file Game.cpp.
References Player::display.
void Game::drawWinAnim (Player * winner)
draws the winning animation on the winning player's display
Parameters
winner the pointer to the player who won the game
Todo:
UNIMPLEMENTED
Definition at line 159 of file Game.cpp.
References Player::display.
bool Game::endGameReached (void)
checks whether the condition for a win has been reached
Returns
true if the win condition has been reached, false otherwise
Test:
Definition at line 170 of file Game.cpp.
References p1, p2, Player::score, and scoreConstrant.
bool Game::playAgain (void)
Prompts the players if they want to play again.
Returns
true if both players want to play again, false otherwise.
Test:
Definition at line 88 of file Game.cpp.
References Player::button, Player::display, Button::get(), p1, p2, and Adafruit_IS31FL3731::printText().
bool Game::ready (void)
prompts the both of the players if they are ready.
Returns
true if both players press their button at prompt, false otherwise.
Todo:
if in a while loop, may need to put the return in a timeout to allow for a responce time or alternatively have the confimation button be the decline button. However, that would muddle its meaning.
Test:
Definition at line 45 of file Game.cpp.
References p1, p2, Player::pot, and Pot::test().
Referenced by Pong::start().
Member Data Documentation
Button* Game::confirmButton private
stores the pointer to the button that isn't assigned to either player.
To call methods on it, instead of exampleButton.printText(...); use exampleButton->printText(...);
Definition at line 11 of file Game.h.
Player* Game::p1 private
stores the pointer to the first player.
To call methods on it, instead of examplePlayer.printText(...); use examplePlayer->printText(...);. To call methods of its members, use examplePlayer->exampleDisplay->printText(...);
Definition at line 9 of file Game.h.
Referenced by chooseDifficulty(), countdown(), displayScore(), endGameReached(), playAgain(), and ready().
Player* Game::p2 private
stores the pointer to the second player.
To call methods on it, instead of examplePlayer.printText(...); use examplePlayer->printText(...);. To call methods of its members, use examplePlayer->exampleDisplay->printText(...);
Definition at line 10 of file Game.h.
Referenced by chooseDifficulty(), countdown(), displayScore(), endGameReached(), playAgain(), and ready().