Pong In A Box: Adafruit_GFX Class Reference
Adafruit_GFX Class Reference abstract
Inherits Print.
Inherited by Adafruit_IS31FL3731, GFXcanvas1, and GFXcanvas16.
Public Member Functions
Adafruit_GFX (int16_t w, int16_t h)
virtual void drawPixel (int16_t x, int16_t y, uint16_t color)=0
virtual void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
virtual void drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
virtual void drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
virtual void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
virtual void fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
virtual void fillScreen (uint16_t color)
virtual void invertDisplay (boolean i)
void drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
void fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
void fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawXBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawChar (int16_t x, int16_t y, unsigned char c, uint16_t color, uint16_t bg, uint8_t size)
void setCursor (int16_t x, int16_t y)
void setTextColor (uint16_t c)
void setTextColor (uint16_t c, uint16_t bg)
void setTextSize (uint8_t s)
void setTextWrap (boolean w)
void setRotation (uint8_t r)
void cp437 (boolean x=true)
void setFont (const GFXfont *f=NULL)
void getTextBounds (char *string, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
void getTextBounds (const __FlashStringHelper *s, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
virtual void write (uint8_t)
int16_t height (void) const
int16_t width (void) const
uint8_t getRotation (void) const
int16_t getCursorX (void) const
int16_t getCursorY (void) const
Protected Attributes
const int16_t WIDTH
const int16_t HEIGHT
int16_t _width
int16_t _height
int16_t cursor_x
int16_t cursor_y
uint16_t textcolor
uint16_t textbgcolor
uint8_t textsize
uint8_t rotation
boolean wrap
boolean _cp437
GFXfont * gfxFont
Detailed Description
Definition at line 12 of file Adafruit_GFX.h.
Constructor & Destructor Documentation
Adafruit_GFX::Adafruit_GFX (int16_t w, int16_t h)
Definition at line 73 of file Adafruit_GFX.cpp.
References _cp437, _height, _width, cursor_x, cursor_y, gfxFont, HEIGHT, rotation, textbgcolor, textcolor, textsize, WIDTH, and wrap.
Member Function Documentation
virtual void Adafruit_GFX::drawPixel (int16_t x, int16_t y, uint16_t color) pure virtual
Implemented in GFXcanvas16, GFXcanvas1, and Adafruit_IS31FL3731.
Referenced by drawBitmap(), drawChar(), drawCircle(), drawCircleHelper(), drawLine(), and drawXBitmap().
void Adafruit_GFX::drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color) virtual
Definition at line 196 of file Adafruit_GFX.cpp.
References _swap_int16_t, and drawPixel().
Referenced by drawFastHLine(), drawFastVLine(), and drawTriangle().
void Adafruit_GFX::drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
Definition at line 245 of file Adafruit_GFX.cpp.
References drawLine().
Referenced by drawRect(), drawRoundRect(), fillCircle(), fillCircleHelper(), and fillRect().
void Adafruit_GFX::drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
Definition at line 251 of file Adafruit_GFX.cpp.
References drawLine().
Referenced by drawRect(), drawRoundRect(), and fillTriangle().
void Adafruit_GFX::drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Definition at line 237 of file Adafruit_GFX.cpp.
References drawFastHLine(), and drawFastVLine().
void Adafruit_GFX::fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Definition at line 257 of file Adafruit_GFX.cpp.
References drawFastVLine().
Referenced by drawChar(), fillRoundRect(), and fillScreen().
void Adafruit_GFX::fillScreen (uint16_t color)
Definition at line 265 of file Adafruit_GFX.cpp.
References _height, _width, and fillRect().
void Adafruit_GFX::invertDisplay (boolean i)
Definition at line 879 of file Adafruit_GFX.cpp.
void Adafruit_GFX::drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Definition at line 88 of file Adafruit_GFX.cpp.
References drawPixel().
void Adafruit_GFX::drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
Definition at line 122 of file Adafruit_GFX.cpp.
References drawPixel().
Referenced by drawRoundRect().
void Adafruit_GFX::fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Definition at line 158 of file Adafruit_GFX.cpp.
References drawFastVLine(), and fillCircleHelper().
void Adafruit_GFX::fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
Definition at line 165 of file Adafruit_GFX.cpp.
References drawFastVLine().
Referenced by fillCircle(), and fillRoundRect().
void Adafruit_GFX::drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Definition at line 296 of file Adafruit_GFX.cpp.
References drawLine().
void Adafruit_GFX::fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Definition at line 304 of file Adafruit_GFX.cpp.
References _swap_int16_t, and drawFastHLine().
void Adafruit_GFX::drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
Definition at line 270 of file Adafruit_GFX.cpp.
References drawCircleHelper(), drawFastHLine(), and drawFastVLine().
void Adafruit_GFX::fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
Definition at line 285 of file Adafruit_GFX.cpp.
References fillCircleHelper(), and fillRect().
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, const uint8_t * bitmap, int16_t w, int16_t h, uint16_t color)
Definition at line 384 of file Adafruit_GFX.cpp.
References drawPixel(), and pgm_read_byte.
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, const uint8_t * bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
Definition at line 402 of file Adafruit_GFX.cpp.
References drawPixel(), and pgm_read_byte.
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, uint8_t * bitmap, int16_t w, int16_t h, uint16_t color)
Definition at line 419 of file Adafruit_GFX.cpp.
References drawPixel().
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, uint8_t * bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
Definition at line 435 of file Adafruit_GFX.cpp.
References drawPixel().
void Adafruit_GFX::drawXBitmap (int16_t x, int16_t y, const uint8_t * bitmap, int16_t w, int16_t h, uint16_t color)
Definition at line 454 of file Adafruit_GFX.cpp.
References drawPixel(), pgm_read_byte, and write().
void Adafruit_GFX::drawChar (int16_t x, int16_t y, unsigned char c, uint16_t color, uint16_t bg, uint8_t size)
Definition at line 525 of file Adafruit_GFX.cpp.
References _cp437, _height, _width, drawPixel(), fillRect(), gfxFont, pgm_read_byte, pgm_read_pointer, and pgm_read_word.
Referenced by Game::chooseDifficulty(), Game::countdown(), loop(), Game::playAgain(), Adafruit_IS31FL3731::printText(), and write().
void Adafruit_GFX::setCursor (int16_t x, int16_t y)
Definition at line 614 of file Adafruit_GFX.cpp.
References cursor_x, and cursor_y.
void Adafruit_GFX::setTextColor (uint16_t c)
Definition at line 631 of file Adafruit_GFX.cpp.
References textbgcolor, and textcolor.
void Adafruit_GFX::setTextColor (uint16_t c, uint16_t bg)
Definition at line 637 of file Adafruit_GFX.cpp.
References textbgcolor, and textcolor.
void Adafruit_GFX::setTextSize (uint8_t s)
Definition at line 627 of file Adafruit_GFX.cpp.
References textsize.
void Adafruit_GFX::setTextWrap (boolean w)
Definition at line 642 of file Adafruit_GFX.cpp.
References wrap.
void Adafruit_GFX::setRotation (uint8_t r)
Definition at line 650 of file Adafruit_GFX.cpp.
References _height, _width, HEIGHT, rotation, and WIDTH.
Referenced by setup().
void Adafruit_GFX::cp437 (boolean x = true)
Definition at line 673 of file Adafruit_GFX.cpp.
References _cp437.
void Adafruit_GFX::setFont (const GFXfont * f = NULL)
Definition at line 677 of file Adafruit_GFX.cpp.
References cursor_y, and gfxFont.
void Adafruit_GFX::getTextBounds (char * string, int16_t x, int16_t y, int16_t * x1, int16_t * y1, uint16_t * w, uint16_t * h)
Definition at line 693 of file Adafruit_GFX.cpp.
References _height, _width, gfxFont, pgm_read_byte, pgm_read_pointer, textsize, and wrap.
void Adafruit_GFX::getTextBounds (const __FlashStringHelper * s, int16_t x, int16_t y, int16_t * x1, int16_t * y1, uint16_t * w, uint16_t * h)
Definition at line 782 of file Adafruit_GFX.cpp.
References _height, _width, gfxFont, pgm_read_byte, pgm_read_pointer, textsize, and wrap.
void Adafruit_GFX::write (uint8_t c) virtual
Definition at line 472 of file Adafruit_GFX.cpp.
References _width, cursor_x, cursor_y, drawChar(), gfxFont, pgm_read_byte, pgm_read_pointer, textbgcolor, textcolor, textsize, and wrap.
Referenced by drawXBitmap().
int16_t Adafruit_GFX::height (void) const
Definition at line 875 of file Adafruit_GFX.cpp.
References _height.
int16_t Adafruit_GFX::width (void) const
Definition at line 871 of file Adafruit_GFX.cpp.
References _width.
uint8_t Adafruit_GFX::getRotation (void) const
Definition at line 646 of file Adafruit_GFX.cpp.
References rotation.
Referenced by Adafruit_IS31FL3731::drawPixel().
int16_t Adafruit_GFX::getCursorX (void) const
Definition at line 619 of file Adafruit_GFX.cpp.
References cursor_x.
int16_t Adafruit_GFX::getCursorY (void) const
Definition at line 623 of file Adafruit_GFX.cpp.
References cursor_y.
Member Data Documentation
const int16_t Adafruit_GFX::WIDTH protected
Definition at line 90 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), GFXcanvas1::fillScreen(), GFXcanvas16::fillScreen(), and setRotation().
const int16_t Adafruit_GFX::HEIGHT protected
Definition at line 90 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), GFXcanvas1::fillScreen(), GFXcanvas16::fillScreen(), and setRotation().
int16_t Adafruit_GFX::_width protected
Definition at line 92 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), drawChar(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), fillScreen(), getTextBounds(), setRotation(), width(), and write().
int16_t Adafruit_GFX::_height protected
Definition at line 92 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), drawChar(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), fillScreen(), getTextBounds(), height(), and setRotation().
int16_t Adafruit_GFX::cursor_x protected
Definition at line 92 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getCursorX(), setCursor(), and write().
int16_t Adafruit_GFX::cursor_y protected
Definition at line 92 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getCursorY(), setCursor(), setFont(), and write().
uint16_t Adafruit_GFX::textcolor protected
Definition at line 95 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), Adafruit_GFX_Button::initButton(), setTextColor(), and write().
uint16_t Adafruit_GFX::textbgcolor protected
Definition at line 95 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), setTextColor(), and write().
uint8_t Adafruit_GFX::textsize protected
Definition at line 97 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getTextBounds(), Adafruit_GFX_Button::initButton(), setTextSize(), and write().
uint8_t Adafruit_GFX::rotation protected
Definition at line 97 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), getRotation(), and setRotation().
boolean Adafruit_GFX::wrap protected
Definition at line 100 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getTextBounds(), setTextWrap(), and write().
boolean Adafruit_GFX::_cp437 protected
Definition at line 100 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), cp437(), and drawChar().
GFXfont* Adafruit_GFX::gfxFont protected
Definition at line 103 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), drawChar(), getTextBounds(), setFont(), and write().
The documentation for this class was generated from the following files:
C:/Users/katabeta/Documents/GitHub/PongInABox/lib/Adafruit-GFX/Adafruit_GFX.h
C:/Users/katabeta/Documents/GitHub/PongInABox/lib/Adafruit-GFX/Adafruit_GFX.cpp