Pong In A Box: C:/Users/katabeta/Documents/GitHub/PongInABox/mains/examples/softpot.cpp File Reference
softpot.cpp File Reference
#include <Adafruit_IS31FL3731.h>
#include <Arduino.h>
#include <string.h>
#include <Reference.h>
#include <Pot.h>
Functions
void setup ()
void loop ()
Variables
Adafruit_IS31FL3731 ledmatrix74 = Adafruit_IS31FL3731()
Adafruit_IS31FL3731 ledmatrix75 = Adafruit_IS31FL3731()
Reference reference = Reference()
Pot pots [] = {Pot(reference.aPin74, &ledmatrix74), Pot(reference.aPin75, &ledmatrix75)}
Function Documentation
void loop ()
Definition at line 28 of file softpot.cpp.
References Adafruit_IS31FL3731::clear(), Reference::potMax, Reference::potMin, and Adafruit_IS31FL3731::setLEDPWM().
void setup ()
Definition at line 15 of file softpot.cpp.
References Reference::address74, Reference::address75, Adafruit_IS31FL3731::begin(), and Adafruit_GFX::setRotation().
Variable Documentation
Adafruit_IS31FL3731 ledmatrix74 = Adafruit_IS31FL3731()
Definition at line 8 of file softpot.cpp.
Adafruit_IS31FL3731 ledmatrix75 = Adafruit_IS31FL3731()
Definition at line 9 of file softpot.cpp.
Pot pots[] = {Pot(reference.aPin74, &ledmatrix74), Pot(reference.aPin75, &ledmatrix75)}
Definition at line 13 of file softpot.cpp.
Reference reference = Reference()
Definition at line 11 of file softpot.cpp.