Pong In A Box: C:/Users/katabeta/Documents/GitHub/PongInABox/mains/examples/solidbutton.cpp File Reference
solidbutton.cpp File Reference
Functions
void setup ()
void loop ()
Variables
Adafruit_IS31FL3731 ledmatrix74 = Adafruit_IS31FL3731()
Adafruit_IS31FL3731 ledmatrix75 = Adafruit_IS31FL3731()
Reference reference = Reference()
uint8_t sweep [] = {1, 2, 3, 4, 6, 8, 10, 15, 20, 30, 40, 60, 60, 40, 30, 20, 15, 10, 8, 6, 4, 3, 2, 1}
bool turn75 = false
bool turn74 = false
Button b1 = Button(reference.dPin74)
Button b2 = Button(reference.dPin75)
Function Documentation
void setup ()
Definition at line 19 of file solidbutton.cpp.
References Reference::address74, Reference::address75, Adafruit_IS31FL3731::begin(), Reference::dPin74, and Reference::dPin75.
void loop ()
Definition at line 35 of file solidbutton.cpp.
References Adafruit_IS31FL3731::clear(), Adafruit_IS31FL3731::drawPixel(), Button::get(), turn74, and turn75.
Variable Documentation
Adafruit_IS31FL3731 ledmatrix74 = Adafruit_IS31FL3731()
Definition at line 6 of file solidbutton.cpp.
Adafruit_IS31FL3731 ledmatrix75 = Adafruit_IS31FL3731()
Definition at line 7 of file solidbutton.cpp.
Reference reference = Reference()
Definition at line 9 of file solidbutton.cpp.
uint8_t sweep[] = {1, 2, 3, 4, 6, 8, 10, 15, 20, 30, 40, 60, 60, 40, 30, 20, 15, 10, 8, 6, 4, 3, 2, 1}
Definition at line 11 of file solidbutton.cpp.
bool turn75 = false
Definition at line 13 of file solidbutton.cpp.
Referenced by loop().
bool turn74 = false
Definition at line 14 of file solidbutton.cpp.
Referenced by loop().
Button b1 = Button(reference.dPin74)
Definition at line 16 of file solidbutton.cpp.
Button b2 = Button(reference.dPin75)
Definition at line 17 of file solidbutton.cpp.